Web/AppWeb/urls.py
from django.urls import path
from AppWeb.views import *
from .views import logout_view
from . import views

urlpatterns = [
    path('', inicio, name='inicio'),
    path('acercaDeMi/', acercaDeMi, name='acercaDeMi'),
    
    path('ConfirmacionDeInformacionGuardada/', confirmacion_guardar),
    
    path('consulta_nueva/', consultas, name= 'consulta_nueva'),
    
    path('buscar_empleado/', buscar_empleado, name='buscar_empleado'),
    
    path('resultados/', resultado_empleado),
    
    #LOGIN
    path('login/', inicioSesion, name="login"),
    path('register/', registro, name="Registro"),
    path('logout/', logout_view, name='logout'),
    path('editar/', editar_usuario, name='editar'),
    path("verConsultas", leerConsultas, name='verConsultas'),
    #Avatar
    path('agregarAvatar', agregarAvatar, name="avatar"),
    

        
    
    #CRUD de empleados
    
    path('empleados/', LeerEmpleados, name= 'Empleados'),
    path('empleadoNuevo/', empleado_nuevo, name='empleado_nuevo'),
    path('EliminarEmpleado<empleadoNombre>', eliminarEmpleado, name= 'EliminarEmpleado'),   
    
    
    #CRUD USANDO CLASES
    
    #Área
    path('Departamento/list/', ListaDepartamento.as_view(), name= 'LeerDepartamento'),
    path('Departamento/<int:pk>/', DetalleDepartamento.as_view(), name= 'DetalleDepartamento'),
    path('Departamento/crear/', CrearDepartamento.as_view(), name= 'CrearDepartamento'),
    path('Departamento/editar/<int:pk>', ActualizarDepartamento.as_view(), name= 'ActualizarDepartamento'),   
    path('Departamento/borrar/<int:pk>', BorrarDepartamento.as_view(), name= 'BorrarDepartamento'),
    
    #Eventos
    path('Eventos/list/', ListaEventos.as_view(), name= 'LeerEventos'),
    path('Eventos/<int:pk>/', DetalleEventos.as_view(), name= 'DetalleEventos'),
    path('Eventos/crear/', CrearEventos.as_view(), name= 'CrearEventos'),
    path('Eventos/editar/<int:pk>', ActualizarEventos.as_view(), name= 'ActualizarEventos'),   
    path('Eventos/borrar/<int:pk>', BorrarEventos.as_view(), name= 'BorrarEventos'),
    
]

Web/Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Web/', include('AppWeb.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/AppWeb/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Empleado(models.Model):
    
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    puesto = models.CharField(max_length=50)
    
    
    def __str__(self):

        return f"{self.nombre} --- {self.apellido} --- {self.puesto}"
    

class Consultas(models.Model):
    usuario = models.CharField(max_length=30)
    titulo = models.CharField(max_length=100)
    fecha = models.DateField()
    descripcion = models.CharField(max_length=1000)

    
    def __str__(self):

        return f"{self.titulo} --- {self.fecha}"


class Departamento(models.Model):
    
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300)
    

    def __str__(self):

        return f"{self.nombre}"
    
class Eventos(models.Model):
    
    nombre = models.CharField(max_length=300)
    descripcion = models.CharField(max_length=300)
    fecha = models.DateField()
    
    def __str__(self):

        return f"{self.nombre}-----{self.fecha}"
    

class Avatar(models.Model):
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True,blank=True)
    

Web/AppWeb/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from AppWeb.models import Avatar, Empleado

class FormularioEmpleado(forms.ModelForm):  # Cambia a ModelForm
    
    class Meta:
        model = Empleado  # Especifica el modelo asociado
        fields = ['nombre', 'apellido', 'puesto']  # Lista los campos que quieres incluir en el formulario
    

    


class FormularioConsultas(forms.Form):
    usuario = forms.CharField(max_length=30)
    titulo = forms.CharField(max_length=100)
    fecha = forms.DateField()
    descripcion = forms.CharField(max_length=1000)



class FormularioDepartamento(forms.Form):
    
    nombre = forms.CharField(max_length=50)
    descripcion = forms.CharField(max_length=300)
    
class FormularioEventos(forms.Form):
    
    nombre = forms.CharField(max_length=300)
    descripcion = forms.CharField(max_length=300)
    fecha = forms.DateField()
    
    
class UsuarioRegistro(UserCreationForm):
    
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget=forms.PasswordInput)
    
    class Meta:
        
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]
        
        
class FormularioEditar(UserCreationForm):
    
        
    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget=forms.PasswordInput)
    
    class Meta:
        
        model = User
        fields = ["email", "first_name", "last_name", "password1", "password2"]


class AvatarFormulario(forms.ModelForm):
    
    class Meta:
        model = Avatar
        fields = ["imagen"]

Web/AppWeb/views.py
from django.shortcuts import render, get_object_or_404
from AppWeb.models import *
from AppWeb.forms import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# Create your views here.
def acercaDeMi(request):
    
    return render(request, 'AppWeb/acercaDeMi.html')

def inicio(request):
    
    return render(request, 'AppWeb/inicio.html', {"Bienvenida":"Bienvenido a mi página."})


def confirmacion_guardar(request):
    
   return render(request, 'AppWeb/confirmacion_guardar.html')

def consultas(request):

    if request.method == "POST":

        formulario = FormularioConsultas(request.POST) #almacena la informacion que se ha puesto en el form

        if formulario.is_valid():

            info_dic = formulario.cleaned_data #convierte la info del form a un diccionario de python

            consulta_nueva = Consultas(
                usuario=info_dic["usuario"],
                titulo=info_dic["titulo"],
                fecha=info_dic["fecha"],
                descripcion=info_dic["descripcion"],
                
                
                )
            
            consulta_nueva.save()
            
            return render(request, "AppWeb/confirmacion_guardar.html")
        
    else:
            
        formulario = FormularioConsultas()
    
    
    
    return render(request, 'AppWeb/consulta_nueva.html', {'formu': formulario})

def leerConsultas(request):
    
    consultas = Consultas.objects.all()
    
    contexto = {"gente":consultas}
    
    return render(request, "AppWeb/verConsultas.html", contexto)
    

@login_required
def empleado_nuevo(request):
    
    if request.method == "POST":

        formulario = FormularioEmpleado(request.POST) #almacena la informacion que se ha puesto en el form

        if formulario.is_valid():

            info_dic = formulario.cleaned_data #convierte la info del form a un diccionario de python

            empleado_nuevo = Empleado(
                nombre=info_dic["nombre"],
                apellido=info_dic["apellido"],
                puesto=info_dic["puesto"],
                
                )
            
            empleado_nuevo.save()
            
            return render(request, "AppWeb/confirmacion_guardar.html")
        
    else:
            
        formulario = FormularioEmpleado()
    
    
    
    return render(request, 'AppWeb/empleado_nuevo.html', {'formu': formulario})



def buscar_empleado(request):
    
    return render(request, "AppWeb/buscar_empleado.html")


def resultado_empleado(request):
    
    empleado = request.GET["empleado"]
    
    resultados = Empleado.objects.filter(nombre__iexact=empleado)
    
    return render(request, 'AppWeb/resultado_empleado.html', {'resultados':resultados})

def LeerEmpleados(request):
    
    empleados = Empleado.objects.all()
    
    contexto = {"trabajadores" : empleados}
    
    
    return render(request, "AppWeb/empleado.html", contexto)



def eliminarEmpleado(request, empleadoNombre):
    # Verificar si se ha enviado una solicitud POST
    if request.method == 'POST':
        # Obtener el ID del empleado que se va a eliminar
        empleado_id = request.POST.get('empleado_id')
        # Obtener el empleado específico por su ID
        empleado = get_object_or_404(Empleado, id=empleado_id)
        # Eliminar el empleado
        empleado.delete()
    
    # Obtener nuevamente la lista de empleados después de la eliminación
    empleados_actualizados = Empleado.objects.all()
    
    contexto = {"trabajadores": empleados_actualizados}
    
    return render(request, "AppWeb/buscar_empleado.html", contexto)

# VIEWS BASADAS EN CLASES


# Área
class ListaDepartamento(LoginRequiredMixin, ListView):
    
    model = Departamento
    
    
class DetalleDepartamento(LoginRequiredMixin, DetailView):
    
    model = Departamento
    
class CrearDepartamento(LoginRequiredMixin, CreateView):
    
    model = Departamento
    success_url = "/Web/Departamento/list"
    fields = ["nombre", "descripcion"]
    
    
class ActualizarDepartamento(LoginRequiredMixin, UpdateView):
     
    model = Departamento
    success_url = "/Web/Departamento/list"
    fields = ["nombre", "descripcion"]
    
class BorrarDepartamento(LoginRequiredMixin, DeleteView):
    
    model = Departamento
    success_url = "/Web/Departamento/list"
    
    
    
    
#Eventos
class ListaEventos(LoginRequiredMixin, ListView):
    
    model = Eventos
    
    
class DetalleEventos(LoginRequiredMixin, DetailView):
    
    model = Eventos
    
class CrearEventos(LoginRequiredMixin, CreateView):
    
    model = Eventos
    success_url = "/Web/Eventos/list"
    fields = ["nombre", "descripcion", "fecha"]
    
    
class ActualizarEventos(LoginRequiredMixin, UpdateView):
     
    model = Eventos
    success_url = "/Web/Eventos/list"
    fields = ["nombre", "descripcion", "fecha"]
    
class BorrarEventos(LoginRequiredMixin, DeleteView):
    
    model = Eventos
    success_url = "/Web/Eventos/list"
    
    
#LOGIN Y REGISTRO


def inicioSesion(request):
    
    if request.method =="POST":
        
        form = AuthenticationForm(request, data = request.POST)
        
        if form.is_valid():
            
            usuario = form.cleaned_data.get("username")
            
            contra=form.cleaned_data.get("password")
            
            user = authenticate(username = usuario, password = contra)
            
            if user:
                
                login(request, user)
                
                return render(request, "AppWeb/inicio.html", {"mensaje":f"Bienvenido {user}"})
            
        else:
            
            return render(request, "AppWeb/inicio.html", {"mensaje":"Datos incorrectos."})
        
    else: 
        
        form = AuthenticationForm()
        
    
    return render(request, "AppWeb/login.html", {"formu":form})


def registro(request):
    
    if request.method =="POST":
        
        form = UsuarioRegistro(request.POST)
        
        if form.is_valid():
            
            username = form.cleaned_data["username"]
            form.save()
            return render(request,"AppWeb/inicio.html", {"mensaje":"Usuario Creado."})
        
    else: 
        
        form = UsuarioRegistro()
        
    
    return render(request, "AppWeb/registro.html", {"formu":form})

@login_required
def editar_usuario(request):
    
    usuario = request.user
    
    if request.method == "POST":
        
        form = FormularioEditar(request.POST)
        
        if form.is_valid():
            
            info = form.cleaned_data
            
            usuario.email = info["email"]
            usuario.set_password(info["password1"])
            usuario.firs_name = info["first_name"]
            usuario.last_name = info["last_name"]
            
            usuario.set_password(info["password1"])
            
            usuario.save()
            
            return render(request, "AppWeb/inicio.html")
        
    else:
        
        form = FormularioEditar(initial={
            "email":usuario.email,
            "first_name":usuario.first_name,
            "last_name":usuario.last_name,
            
        })
        
    return render(request, "AppWeb/editarperfil.html", {"form":form, "usuario":usuario})


def logout_view(request):
    
    logout(request)
    return render(request, "AppWeb/inicio.html", {"mensaje":"Se ha cerrado sesión"})
    

@login_required
def agregarAvatar(request):
    
    if request.method == "POST":
        
        form = AvatarFormulario(request.POST, request.FILES)
        
        if form.is_valid():
            
            usuarioActual = User.objects.get(username=request.user)
            avatar = Avatar(usuario=usuarioActual, imagen=form.cleaned_data["imagen"])
            
            avatar.save()
            return render(request, "AppWeb/inicio.html", {"mensaje":"Se agregó el avatar con éxito."})
        
    else:
        form = AvatarFormulario
        
    return render(request, "AppWeb/agregarAvatar.html", {"formulario":form})




    
    

Web/AppWeb/templates/AppWeb/acercaDeMi.html
{% extends 'AppWeb/padre.html'%}

{% load static %}



{% block pregunta %}

<p style="color: black;">Mi nombre es Gonzalo Conti, soy de Buenos Aires, Argentina. Tengo 26 años y esta es la primera página web que he construído.
    Si queres ponerte en contacto conmigo mi mail es: gonzaloconti@hotmail.com.
</p>

{% endblock %}



{% block copy %}
    
    <div class="container px-5"><p class="m-0 text-center text-black">Copyright &copy; Gonzalo Conti 2024 <a href="#!"> Acerca de mi </a></p></div>
    
{% endblock %}

Web/AppWeb/templates/AppWeb/agregarAvatar.html
{% extends 'AppWeb/padre.html'%}

{% load static %}

{% block titulo %}

<p style="color: black;">Acá podes agregar tu imagen de perfil</p>

{% endblock %}

{% block pregunta %}
    
{% endblock %}

{% block parrafo %}

<div style="display: flex; justify-content: center">
</div>
<br>
<div style="display: flex; justify-content: center">

    <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

        {{formulario.as_p}}

        <button type="submit">Agregar avatar</button>
    </form>
    
    
</div>

<div class="container px-5"><p class="m-0 text-center text-black">Copyright &copy; Gonzalo Conti 2024 <a href="#!"> Acerca de mi </a></p></div>
{% endblock %}

{% block copy %}

    

{% endblock %}

Web/AppWeb/templates/AppWeb/cambiar_contra.html
{% extends 'AppWeb/padre.html'%}



{% block titulo %}
<p style="color: black;">Cambiar Contraseña</p>

{% endblock %}

{% block botones %}

    <style>
    /* Estilo para los nombres de los formularios */
        form label {
            color: rgb(0, 0, 0); /* Cambia el color */
        }
    </style>

    <form action="" method="POST"> {% csrf_token %}

        {{form.as_p}}

        <button type="submit">Cambiar contraseña</button>
    </form>

{% endblock %}


{% block copy %}

    <div class="container px-5"><p class="m-0 text-center text-black">Copyright &copy; Gonzalo Conti 2024</p></div>

{% endblock %}

Web/AppWeb/templates/AppWeb/confirmacion_guardar.html
{% extends 'AppWeb/padre.html'%}



{% block titulo %}

<p style="color: black;">¡Se ha guardado la información con éxito!</p>

{% endblock %}


{% block copy %}

    <div class="container px-5"><p class="m-0 text-center text-black">Copyright &copy; Gonzalo Conti 2024</p></div>

{% endblock %}

Web/AppWeb/templates/AppWeb/consulta_nueva.html
{% extends 'AppWeb/padre.html'%}

{% block titulo %}
<p style="color: black;">Aquí puede realizar una nueva consulta</p>
{% endblock %}

{% block parrafo %}

<div style="display: flex; justify-content: center">
    <form action="" method="post"> {% csrf_token %}
    
        {{formu}}
    <br>
        <input type="submit" value="Guardar">
        <button>
            <a href="{% url 'verConsultas' %}">Ver Consultas</a>
        </button>
    
    </form>
</div>
<br>

{% endblock %}

Web/AppWeb/templates/AppWeb/departamento_confirm_delete.html
{% extends 'AppWeb/padre.html'%}

{% block titulo %}
<p style="color: black;">Eliminando el área.</p>
{% endblock %}

{% block parrafo %}
<div style="display: flex; justify-content: center">
</div>
<br>
<div style="display: flex; justify-content: center">
    
    <ol>
        
        <form action="" method="POST"> {% csrf_token %}

            <p>¿Estás seguro que quieres eliminar esta área?</p>
            <input type="submit" value="Eliminar">
    
        </form>
    </ol>
</div>

{% endblock %}

Web/AppWeb/templates/AppWeb/departamento_list.html
{% extends 'AppWeb/padre.html'%}

{% block titulo %}
<p style="color: black;">Aquí puede ver, crear, editar o borrar áreas de la empresa.</p>
{% endblock %}

{% block parrafo %}
    
    

    <div style="display: flex; justify-content: center">
       </div>
       <br>
       <div style="display: flex; justify-content: center">
           
           <ol>
               {% for departamento in object_list %}
       
           <p>nombre : {{departamento.nombre}}</p>
               
            <button>
               <a href="{% url 'DetalleDepartamento' departamento.id %}"> Ver  </a>
            </button>
            <button>
               <a href="{% url 'ActualizarDepartamento' departamento.id %}"> Editar  </a>
            </button>
            <button>
               <a href="{% url 'BorrarDepartamento' departamento.id %}"> Borrar  </a>
            </button>
       
               
           <br>
           <br>
               --------------------------------------------------------------------
       
           {% endfor %}
       
           <br>
           <br>
       
           <button><a href="{% url 'CrearDepartamento' %}">Crear Departamento</a></button>
               </ol>
       </div>
       

{% endblock %}

Web/AppWeb/templates/AppWeb/editarperfil.html
{% extends 'AppWeb/padre.html'%}



{% block titulo %}
<p style="color: black;">Editar Usuario</p>

{% endblock %}

{% block botones %}

    <style>
    /* Estilo para los nombres de los formularios */
        form label {
            color: rgb(0, 0, 0); /* Cambia el color aquí según tus preferencias */
        }
    </style>

    <form action="" method="POST"> {% csrf_token %}

        {{form.as_p}}

        <button type="submit">Editar</button>
    </form>

{% endblock %}
{% block parrafo %}

{% endblock %}

{% block copy %}

    <div class="container px-5"><p class="m-0 text-center text-dark">Copyright &copy; Gonzalo Conti 2024</p></div>

{% endblock %}

Web/AppWeb/templates/AppWeb/eliminar_empleado.html
{% extends 'AppWeb/padre.html'%}


{% block titulo %}
<p style="color: black;"><h2>Eliminar Empleado</h2></p>

{% endblock %}

{% block parrafo %}

<p>¿Estás seguro de que deseas eliminar este empleado?</p>
<form action="{% url 'eliminar_empleado' empleado.nombre %}" method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
</form>
<a href="{% url 'empleados' %}">Cancelar</a>

{% endblock %}

Web/AppWeb/templates/AppWeb/empleado_nuevo.html
{% extends 'AppWeb/padre.html'%}


{% block titulo %}
<p style="color: black;">Aquí puede dar de alta un empleado de la empresa</p>

{% endblock %}

{% block parrafo %}

<div style="display: flex; justify-content: center">
    <form action="" method="post"> {% csrf_token %}
    
        {{formu}}
    
        <input type="submit" value="Guardar">
    
    </form>
</div>

{% endblock %}

Web/AppWeb/templates/AppWeb/eventos_list.html
{% extends 'AppWeb/padre.html'%}

{% block titulo %}
<p style="color: black;">Aquí puede ver, crear, editar o borrar eventos de la empresa.</p>
{% endblock %}

{% block parrafo %}
    
    

    <div style="display: flex; justify-content: center">
       </div>
       <br>
       <div style="display: flex; justify-content: center">
           
           <ol>
               {% for evento in object_list %}
       
           <p>nombre : {{evento.nombre}}</p>
               
            <button>
               <a href="{% url 'DetalleEventos' evento.id %}"> Ver  </a>
            </button>
            <button>
               <a href="{% url 'ActualizarEventos' evento.id %}"> Editar  </a>
            </button>
            <button>
               <a href="{% url 'BorrarEventos' evento.id %}"> Borrar  </a>
            </button>
       
               
           <br>
           <br>
               --------------------------------------------------------------------
       
           {% endfor %}
       
           <br>
           <br>
            <button><a href="{% url 'CrearEventos' %}">Nuevo evento</a></button>
           
               </ol>
       </div>


{% endblock %}

Web/AppWeb/templates/AppWeb/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Mi Página</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppWeb/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'inicio' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                        
                        {% if request.user.is_authenticated %}

                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'LeerEventos' %}">Eventos</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'LeerDepartamento' %}">Área</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Empleados' %}">Empleados</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'consulta_nueva' %}">Consultas</a></li>
                    
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'editar' %}">Editar Usuario</a></li>
                    
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Cerar Sesión</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page">Hola, {{user.username}}</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'avatar' %}">Agregar avatar</a></li>
                        
                        {% with first_image=user.avatar_set.first %}

                            {% if first_image %}
                            <a href="{{ first_image.imagen.url }}" target="_blank"></a>
                            <img src="{{ first_image.imagen.url }}" class="" style="max-width: 50px;">
                        
                            {% endif %}
                        {% endwith %}
                        

                        {% endif %}

                        

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        
        <header class="bg-white py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            
                            <h1 class="display-7 fw-bolder text-white mb-2">
                            {% block titulo %}

                            {% endblock %}        
                            </h1>
                            <h4 class="display-20 fw-bolder text-white mb-2">
                            {% block pregunta %}

                            {% endblock %}
                            </h4>
                            
                            {% block botones %}
                            
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-white">
            {% block parrafo %}

            {% endblock %}
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
    

    
    <div class="container px-5"><p class="m-0 text-center text-black">Copyright &copy; Gonzalo Conti 2024 <a href="{% url 'acercaDeMi' %}"> Acerca de mi </a></p></div>
    
</html>

Web/AppWeb/templates/AppWeb/resultado_empleado.html
{% extends 'AppWeb/padre.html'%}


{% block titulo %}
<p style="color: black;">Aquí puede dar de alta un empleado de la empresa</p>
{% endblock %}


{% block botones %}
<div style="display: flex; justify-content: center">
 <h4>Los empleados con ese nombre son:</h4>
</div>
<br>
<div style="display: flex; justify-content: center">
    
    <ol>
        {% for empleado in resultados %}
        <li>Nombre y apellido: {{ empleado.nombre }} {{ empleado.apellido }} - Puesto: {{ empleado.puesto }} </li>
        <form action="{% url 'EliminarEmpleado' empleado.nombre %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="empleado_id" value="{{ empleado.id }}">
            <button type="submit">Eliminar</button>
        </form>
        {% endfor %}   
        </ol>
</div>

{% endblock %}

<a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'editarEmpleado' empleado.nombre %}">Editar Información de un empleado</a>

Web/AppWeb/templates/AppWeb/verConsultas.html
{% extends 'AppWeb/padre.html'%}

{% load static %}

{% block titulo %}
<p style="color: black;">Iniciar sesión</p>


{% endblock %}

{% block pregunta %}
    
{% endblock %}

{% block botones %}

{% for empleado in gente %}

<p>Nombre = {{empleado.usuario}}</p>
<p>Titulo = {{empleado.titulo}}</p>
<p>Fecha = {{empleado.fecha}}</p>
<p>Descripcion = {{empleado.descripcion}}</p>

------------------------------------------------------

{% endfor %}
{% endblock %}